spring.application.name=Gazette-Management-NIC


spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=jdbc:postgresql://localhost:5434/gazette_management_26022026
# spring.datasource.url=jdbc:postgresql://localhost:5432/megpns_01042026
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:postgresql://10.179.9.71:5432/megpns
#spring.datasource.username=megpnsuser
#spring.datasource.password=megpns
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.servlet.session.timeout=30m
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.name=JSESSIONID
server.servlet.session.cookie.secure=true    
server.servlet.session.cookie.same-site=strict
server.servlet.session.tracking-modes=cookie
spring.jpa.show-sql=false
server.servlet.session.cookie.max-age=-1


server.port=8089


#server.servlet.context-path=/megpns


server.error.whitelabel.enabled=false



spring.thymeleaf.cache=true



logging.level.org.springframework.security=INFO


spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB



server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never
server.error.include-exception=false
server.server-header=


server.error.path=/error


spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false




server.tomcat.uri-encoding=UTF-8
server.tomcat.allow-backslash=false



