spring.application.name=Gazette-Management-NIC
#spring.application.name=Auth-Test


spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/Gazette-Management-NIC
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true


server.port=8081



server.error.whitelabel.enabled=false



# Thymeleaf Cache (disable caching during development)
spring.thymeleaf.cache=false


logging.level.org.springframework.security=DEBUG





# Set max file size to 5MB
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
